### ISSUE TITLE
Unable to find printer QL 820 NWB

### ISSUE THREAD

**Issue by gauravsaini03** [AboboSoftware/cordova-plugin-brother-label-printer#26]
Hello Team,

Thanks for building this awesome plugin. 

We are successfully able to print with QL 720 NW printer using this plugin. But recently, we tried with QL 820 NWB printer somehow the findNetworkPrinters() function is not returning any list of printer in the network. 

Just to check if printer is connected properly, we tried printing a label using the Brother application(https://play.google.com/store/apps/details?id=com.brother.ptouch.iprintandlabel&hl=en_IN) and it worked perfectly fine. 

We tried using tried finding printer via Bluetooth method also, but still an empty list comes. 

I am currently stuck and not able to understand why the same code is able to detect QL-720-NW but not QL-820-NWB and in the ReadMe file i read it is tested on these two printers. 

Any suggestions will be really helpful. 

Regards,
Gaurav

**Comment by arcadius** [comment]
@gauravsaini03 , I own an  QL-820-NWB and I can confirm this plugin works perfectly.

I have seen circumstances where ```findNetworkPrinters()```
fails due to network security issues.

Please try using a static IP and see.

Note using a static IP will avoid extra network lookup.

**Comment by robr2112** [comment]
Also make sure that you've added ALL printer models that you wish to detect to the array of printer names you pass to findNetworkPrinters.

BTW: I notice at least the iOS SDK being distributed with the plugin is downlevel (3.1.1 vs 3.1.12). But, support for QL-820NWB was added around 3.0.7. So, the version included should work with QL-820NWB.

**Comment by gauravsaini03** [comment]
@robr2112 @arcadius  Thanks a lot for your reply. 

I will try with the Static IP but I don't think that will be an issue, because on the same device using Brother Label printer App it was able to detect printer and even a print a badge. Just from the app it will not detecting. 
Also, I have added the printer model name in findNetworkPrinters.

**Comment by arcadius** [comment]
Closing as it has been stale for some time.... Feel free to reopen if this issue persists
