### ISSUE TITLE
React native version

### ISSUE THREAD

**Issue by frankieb93** [AboboSoftware/cordova-plugin-brother-label-printer#52]
Is there a version for react native?

**Comment by robr2112** [comment]
Hi @frankieb93, 
Currently there is NOT a supported RN plugin available. But, we are investigating solutions.

We would love to know more about what you are doing and assist you as possible.
Please sign up for our free Developer Program here:
https://developerprogram.brother-usa.com

If you are outside the US, please send email to SDKSupport@brother.com to provide details about your project, and we can try to connect you to the appropriate resources.

-Rob

**Comment by arcadius** [comment]
Hello @frankieb93 
As @robr2112 said above, this plugin is only for cordova/capacitor/ionic related projects.

Google would be your best friend.
BTW, Google brought up this one 
https://github.com/Avery246813579/react-native-brother-printers
Give it a go and see if it works for you
