### ISSUE TITLE
Finding Label Names

### ISSUE THREAD

**Issue by cpgb85** [AboboSoftware/cordova-plugin-brother-label-printer#53]
I see there is a list of supported label names, but where do I find on the actual label itself what it is?  The only thing i see is dk-2251

**Comment by arcadius** [comment]
see https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer#interface-reference
Its `W62RB`

**Comment by cpgb85** [comment]
> see https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer#interface-reference Its `W62RB`

 How do I know that though?

**Comment by arcadius** [comment]
https://support.brother.co.jp/j/s/support/html/mobilesdk/reference/android/labelinfo.html

On the box, it says 62mm and red/black

**Comment by arcadius** [comment]
Closing as issues seems to be resolved
