### ISSUE TITLE
Double label printing issue when printing with bluetooth

### ISSUE THREAD

**Issue by aruntube** [AboboSoftware/cordova-plugin-brother-label-printer#55]
When i print with Bluetooth the label is printing twice (Duplicated).

**Comment by robr2112** [comment]
Which printer model?

Does the papersize info/type match the paper you are actually using?

**Comment by aruntube** [comment]
I am using QL-820NWB Printer. I kept PaperLabelName : 62mm in the printer options and using same 62mm label for printing.

**Comment by risip204** [comment]
Can you verify if the label in use is DK-2205? (Continuous roll). 
Does this occur specifically when printing over Bluetooth? Have you tried print over Wi-Fi to verify this is strictly with Bluetooth communication?
When you set the scale mode (fit to page), it usually compress the data into single label. Please check if the "NumberofCopies" is not set.
Lastly if you can share the code snippet, I can have a look to see if there is anything that could be causing this issue.

**Comment by arcadius** [comment]
@aruntube 
I have seen similar issues before.
It is likely to be a front-end issue.
Please put a logging message right on the user tap/click event and you will notice that the even is fired twice.
So, that has nothing to do with the printing process.

The way this is handles is that you disable the print button once it's clicked and make sure you capture only one event.
It's likely to be a UI issue.

**Comment by aruntube** [comment]
@arcadius Yes its a font-end issue. Thank you @robr2112 @risip204 @arcadius
